GUI zur erstellung von fragen
lomma01/isef-brainbear pull request #25
Opened 2022-04-03 12:54 UTC by preter92

Funktionen sind noch keine implementiert

2022-04-04 17:31 UTC, xamid1g commented
die database.db und pychace sollten nicht gemerged werden. Die hätte man vll nicht commiten sollen^^

2022-04-04 17:39 UTC, lomma01 requested changes
Bitte database.db von commit ausschließen

2022-04-05 13:38 UTC, Sapor2010 approved these changes
fine

2022-04-05 15:14 UTC, lomma01 approved these changes

2022-04-05 15:16 UTC, merged